name: Build

on:
  [push, workflow_dispatch]:
    branches:
      - main


jobs:
  build:
    uses: Mazaadak/.github/.github/workflows/java-build-package-push.yml@main
    with:
      java-version: '21'
      skip-tests: true